baseURL = "https://blog.pickledchair.com/"
languageCode = "ja-jp"
title = "Chaos in the SuitCase"
paginate = "10"
theme = "mainroad"
hasCJKLanguage = true
defaultContentLanguage = "ja"
googleAnalytics = "G-FVF3WNH3P3"

[Author]
  name = "Gray SuitCase"
  bio = "大学を卒業しましたが、メンタル的に問題がありまだ働いていません。趣味はプログラミングとクラシック音楽関連（演奏も鑑賞も好き）。最近は数学への興味も芽生えました。"
  avatar = "img/avatar.png"

[Params]
  subtitle = "趣味についての色々。"
  description = "Gray SuitCase's personal blog"
  copyright = "Gray SuitCase"
  images = ["img/ogp.png"]
  opengraph = true
  schema = true
  twitter_cards = true
  customCSS = ["css/custom.css", "https://use.fontawesome.com/releases/v5.0.6/css/all.css"]
  readmore = true
  authorbox = true
  toc = false
  pager = true
  post_meta = ["date", "categories"]
  dateformat = "2006-01-02"
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  googleFontsLink = "https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap"

[Params.style.vars]
  highlightColor = "#769bb5"

  fontFamilyPrimary = "'Noto Sans JP', sans-serif"

[Params.logo]
  image = "img/logo.png"
  title = "Chaos in the SuitCase"
  subtitle = "趣味についての色々。"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5
  categories_counter = false
  tags_counter = true

[[menu.main]]
  name = "TOP"
  url = "/"
  weight = 1

[[menu.main]]
  name = "TECH"
  url = "/categories/技術/"
  weight = 2

[[menu.main]]
  name = "LIFE"
  url = "/categories/生活/"
  weight = 3

[[menu.main]]
  name = "ABOUT"
  url = "/about"
  weight = 4

[Params.widgets.social]
  twitter = "pickled_chair"
  github = "PickledChair"

[[menu.footer]]
  name = "プライバシーポリシー"
  url = "/privacy"

